name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: build docker image
      run: docker build -f Dockerfile.pibuilder -t pibuilder .

    - name: Build
      run: ./script/build.arm7
